### ISSUE TITLE
Infinite loop when you start the game...

### ISSUE THREAD

**Issue by cbotman** [AlexStiles7869/zombie_dice#2]
Once you start the game, it's playing itself for a couple turns then hits an infinite loop. I haven't tried debugging the code yet, just thought it'd be fun to open an issue. 😉

Here's an example run:
```
zombie_dice ./main.py 
What is the player's name? Foo
What is the player's age? 10
What is the player's name? Bar 
What is the player's age? 12
Bar
You pick 3 random dice out of the cup and get:

True True
A green die.

A orange die.

A red die.

1 1
2 2
3 3
You pick 3 random dice out of the cup and get:

False True
You pick 3 random dice out of the cup and get:

True True
A green die.

A red die.

A red die.

1 1
2 2
3 3
You pick 3 random dice out of the cup and get:

False True
You pick 3 random dice out of the cup and get:

False True
You pick 3 random dice out of the cup and get:

False True
You pick 3 random dice out of the cup and get:

False True
You pick 3 random dice out of the cup and get:
^C
```

**Comment by AlexStiles7869** [comment]
An issue! Never had one of these before (on Github, I often have issues with my code). I've been working on this over the last couple days. Almost all of the code that was implementing this very basic game loop is gone. I'll push an update tomorrow, so don't do anything major till then.

**Comment by AlexStiles7869** [comment]
Game is in functioning state now.
