### ISSUE TITLE
Copy changes e.g. "Would you like to roll again?"

### ISSUE THREAD

**Issue by cbotman** [AlexStiles7869/zombie_dice#7]
At the end of each roll, it asks "Would you like to continue playing?".

I suggest changing this to "Roll again?" or "Would you like to roll again?"

I also noticed when you catch a brain it says "You collected 1 brains", but should be "You collected 1 brain" with the 's' conditional.

**Comment by AlexStiles7869** [comment]
I've changed the question phrasing to "Roll again?", less stiff, and added conditional application of pluralisation.
