### ISSUE TITLE
Allow seeding the random number generator

### ISSUE THREAD

**Issue by cbotman** [AlexStiles7869/zombie_dice#8]
To assist with debugging (especially unit tests), it would be handy to be able to seed the random number generator. WHen a seed is set, random() will return the same series of numbers each time (if the same seed is used(. This way, the game can be replayed with the same outcome. 

You just have to call seed() before fetching any random numbers. 

You can see an example here: https://github.com/cbotman/dear-automaton/blob/c518ceb5b7550a03d55f938ad1770f5bdef11ce7/elementary.py#L81

**Comment by AlexStiles7869** [comment]
I've added this in and copied your method of using a command-line argument. It seems that seeding carries across imports to other modules which is handy.
