### ISSUE TITLE
"Turns" versus "Rounds"

### ISSUE THREAD

**Issue by cbotman** [AlexStiles7869/zombie_dice#9]
I'm not sure about this, but just putting it out there.

Say I set up a 2 player game, at the moment the first player gets Turn 1, the second player gets Turn 2, and the first player gets Turn 3.

I feel like I'd rather see that Turns 1 and 2 are both part of Round 1, and that turn 3 is actually the start of Round 2.

Perhaps change it to something like so:
```
Round 1 | It is Carbon's turn.
Round 1 | It is John's turn.
Round 2 | It is Carbon's turn.
...
```

Or another way to format it:

```
--------------------
Turn 2 | It is Carbon's turn.
Current Brains | 0
--------------------
GREEN: You collected 1 brains, you would now have 1 brains if you banked.
GREEN: You collected 1 brains, you would now have 2 brains if you banked.
RED: The person you were chasing ran away!
----------
Would you like to continue playing? no
###############
Round 2
###############
--------------------
Turn 3 | It is John's turn.
Current Brains | 0
--------------------
GREEN: The person you were chasing ran away!
RED: You collected 1 shots, you now have 1 shots.
ORANGE: You collected 1 brains, you would now have 1 brains if you banked.
```

**Comment by AlexStiles7869** [comment]
That's a good idea, much more clear now where you are at in the game. I've changed it to fit your first example for now but might do something more complicated at a later point, possibly when implementing multiple losers, etc.
